### ISSUE TITLE
Deadlink for roadmap in README

### ISSUE THREAD

**Issue by klion26** [katanemo/archgw#306]
the link for Roadmap in README does not exist
![image](https://github.com/user-attachments/assets/7b079c6d-3b92-454b-bcb5-ce6261883b72)

currently, the link is https://github.com/orgs/katanemo/projects/1, and there is no such project there.

![image](https://github.com/user-attachments/assets/0658f9a4-1e7c-49ae-a72d-9f301ce88b1d)

**Comment by salmanap** [comment]
Looking...

**Comment by salmanap** [comment]
Fixed. please review: https://github.com/orgs/katanemo/projects/1/views/1

**Comment by salmanap** [comment]
Also note, we are still working through some internal fixes around stability of builds, leaner dependencies, etc. We will be adding those and doing some additional roadmap items in the short while. Plus some clean-up work on milestones remains
