### ISSUE TITLE
add support for pydantic logfire for LLM/agent tracing

### ISSUE THREAD

**Issue by salmanap** [katanemo/archgw#322]
pydantic logfire is a popular open source observability solution for python apps, and it can collect logs via OTEL - should we should build a demo/test and integrate archgw traces with https://logfire.pydantic.dev/docs/guides/advanced/alternative-clients/?h=otel

see more: https://x.com/samuel_colvin/status/1863160086715113627

**Comment by salmanap** [comment]
This requires adding support for bearer authentication and taking in input on the endpoint from the developer that is not local (4317)

**Comment by salmanap** [comment]
This could be a good issue for @aayushwhiz to crank out...

**Comment by adilhafeez** [comment]
@aayushwhiz you would need to introduce otel-collector. Using otel-collector you can attach auth header before sending tracing to upstream (pydantic, honeycomb or any other api based tracing systems).

In your otel-config you need sth like this,

```
exporters:
  otlp:
    endpoint: "logfire-api.pydantic.dev:443"
    headers:
      "Authorization": "Bearer xxx"
```

Here are some helpful links,

- [otel-collector](https://opentelemetry.io/docs/collector/installation/#docker-compose)
- Sample for how to use [honeycomb in otel collector](https://docs.honeycomb.io/send-data/opentelemetry/collector/),
- Sample on how to use otel [collector with pydanctic ](https://logfire.pydantic.dev/docs/guides/advanced/alternative-clients/#alternative-clients)

**Comment by salmanap** [comment]
@aayushwhiz do we have an ETA on this?

**Comment by aayushwhiz** [comment]
> @aayushwhiz do we have an ETA on this?

Should be done by today eod
