### ISSUE TITLE
Instructions for start-up of arch do not work

### ISSUE THREAD

**Issue by B1tMaster** [katanemo/archgw#349]
Successfully built from source. But when starting the arch, consistently get the error. The configuration file DOES exist in the current directory.. I even tried to provide a full path to it and it still gives this error. in the code, it gets the file from env. but since it prints the correct file name in the correct directory, it must be pulling the file name correctly. 

Is this a bug, or am I doing something wrong?

I have created a virtual env with "uv"  - uv venv .venv --python=python3.12

and then built the project with "uv" as per instructions, but using "uv" 

$ python -m venv venv --python=python3.12
$ source venv/bin/activate   
$ uv pip install archgw==0.1.7

It build successfully . 

Error output on command line: 

2024-12-30 12:14:01,885 - cli.main - INFO - Starting archgw cli version: 0.1.7
2024-12-30 12:14:01,885 - cli.main - INFO - Validating /Users/davramenko/development/aidev/learning/archgw-dev/arch_config.yaml
2024-12-30 12:14:01,889 - cli.main - INFO - Exiting archgw up: validation failed
2024-12-30 12:14:01,889 - cli.main - INFO - Error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

My terminal outputs: 

(.venv) davramenko@Mac-mini archgw % python --version
Python 3.12.8
(.venv) davramenko@Mac-mini archgw %

(.venv) davramenko@Mac-mini archgw % archgw --version
archgw cli version: 0.1.7

starting logs works fine: 
(.venv) davramenko@Mac-mini archgw % archgw logs
2024-12-30 12:08:07,367 - cli.main - INFO - Starting archgw cli version: 0.1.7

arch_config.yaml 👍 
version: v0.1

listener:
  address: 0.0.0.0
  port: 10000
  message_format: huggingface
  connect_timeout: 0.005s

llm_providers:
  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider: openai
    model: gpt-4o

system_prompt: |
  You are a helpful assistant.

prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: >
          Looks like you're curious about my abilities, 
          but I can only provide assistance for currency exchange.

prompt_targets:
  - name: currency_exchange
    description: Get currency exchange rate from USD to other currencies
    parameters:
      - name: currency_symbol
        description: The currency that needs conversion
        required: true
        type: str
        in_path: true
    endpoint:
      name: frankfurther_api
      path: /v1/latest?base=USD&symbols={currency_symbol}
    system_prompt: |
      You are a helpful assistant. Show me the currency symbol you want to convert from USD.

  - name: get_supported_currencies
    description: Get list of supported currencies for conversion
    endpoint:
      name: frankfurther_api
      path: /v1/currencies

endpoints:
  frankfurther_api:
    endpoint: api.frankfurter.dev:443
    protocol: https

**Comment by salmanap** [comment]
Thanks for reporting this. And sorry for the inconvenience. We definitely need to improve error reporting. This error is often due to issues with Docker Desktop or Docker being improperly configured. Here are some steps to troubleshoot and resolve the issue:

Check the Docker socket:

`ls -la ~/Library/Containers/com.docker.docker/Data/docker.sock`

If the socket is missing, Docker Desktop may not be running correctly. Restart Docker Desktop.

**Comment by B1tMaster** [comment]
I tried a different command and I see this output. maybe its' helpful to debug: 

(venv) davramenko@Mac-mini archgw % (venv) davramenko@Mac-mini archgw % ls -la ~/Library/Containers/com.docker.docker/Data/
total 8
drwxr-xr-x@ 39 davramenko  staff  1248 Dec 30 16:06 .
drwxr-xr-x@  7 davramenko  staff   224 Dec 28 13:56 ..
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 backend.sock
drwxr-xr-x@  3 davramenko  staff    96 Oct 18 17:35 buildstore
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 container-filesystem.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 control-init.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 debug-socketforwarder.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 devenv-volumes.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 diagnosticd.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 dns-forwarder.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 docker-api-proxy-control.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 docker-cli.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 docker-desktop-build.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 docker-dev-env-api.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 docker.raw.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 ethernet-fd.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 ethernet-vfkit.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 ethernet-vpnkit.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 extension-manager.sock
drwxr-xr-x@  2 davramenko  staff    64 Oct 18 17:35 extensions
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 filesystem-event.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 filesystem-fd.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 filesystem-volume.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 httpproxy.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 image-inspector.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 lifecycle-server.sock
-rw-r--r--   1 davramenko  staff     3 Dec 30 16:06 locked-directories
drwxr-xr-x@  4 davramenko  staff   128 Oct 18 17:35 log
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 modules-manager.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 mutagen-conduit.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 perf-socketforwarder.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 stats.sock
drwxr-xr-x@  4 davramenko  staff   128 Dec 30 16:06 tasks
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 transfused.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 virtualization.sock
drwxr-xr-x@  3 davramenko  staff    96 Oct 18 17:35 vms
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 volume-contents.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 vpnkit-bridge-fd.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:06 webgpu.sock

**Comment by B1tMaster** [comment]
basically:  
rwxr-xr-x   1 davramenko  staff     0 Dec 30 16:14 docker-cli.sock
srwxr-xr-x   1 davramenko  staff     0 Dec 30 16:14 docker.raw.sock

these two exist but no: docker.sock

**Comment by B1tMaster** [comment]
I created a link just in case to test:

Mac-mini archgw % ls -la ~/Library/Containers/com.docker.docker/Data/docker.sock

now my link points to : backend.sock
 /Users/davramenko/Library/Containers/com.docker.docker/Data/docker.sock -> /Users/davramenko/Library/Containers/com.docker.docker/Data/backend.sock

but I still get the same error.

**Comment by B1tMaster** [comment]
Ok, I seem to fix the previous error after looking on internet and had to enable an "advanced" option in docker desktop. 

<img width="1572" alt="Screenshot 2024-12-30 at 4 42 46 PM" src="https://github.com/user-attachments/assets/b273b2a0-cd39-4f11-830e-0df722fefb54" />

Need to allow the default docker socket to be used..  

But now I have a new problem when I try to start the project: 

(venv) davramenko@Mac-mini archgw % archgw up arch_config.yaml
2024-12-30 16:48:18,933 - cli.main - INFO - Starting archgw cli version: 0.1.7
2024-12-30 16:48:18,933 - cli.main - INFO - Validating /Users/davramenko/development/aidev/learning/archgw/arch_config.yaml
/Users/davramenko/development/aidev/learning/archgw/venv/lib/python3.12/site-packages/docker/credentials/store.py:21: UserWarning: docker-credential-osxkeychain not installed or not available in PATH
  warnings.warn(
2024-12-30 16:48:18,950 - cli.main - INFO - Exiting archgw up: validation failed
2024-12-30 16:48:18,950 - cli.main - INFO - Error: Credentials store error: StoreError('docker-credential-osxkeychain not installed or not available in PATH')

This one I also solved by installing: 

"brew install docker-credential-helper" 

Now the server is starting! Please you can update your instructions for those who come after me :-) problem solved.

**Comment by salmanap** [comment]
Thanks @B1tMaster - really appreciate you sharing the steps that made it work for you. But I think there are several fixes we need here.

1. First investigate if the newly added docker python client is the right way to go for our cli. This requires the advanced setup
2. Update the README with troubleshooting steps. 

Created issues for both https://github.com/katanemo/archgw/issues/351 and https://github.com/katanemo/archgw/issues/352
